### ISSUE TITLE
HistoricalRequestFormatter HistoricalDataTimeFormat Incorrect

### ISSUE THREAD

**Issue by hunterfries** [mathpaquette/IQFeed.CSharpApiClient#32] opened 2019-03-17 17:34 UTC
HistoricalRequestFormatter HistoricalDataTimeFormat is currently hhmmss, but the IQ Feed api documentation states the format should be HHmmSS. This is causing any filter date past 12p to be invalid.

**Comment by mathpaquette** [comment] 2019-03-18 16:56
@hunterfries please give me more details about the request you trying to do.

**Comment by hunterfries** [comment] 2019-03-18 17:03
I'm trying to make a ReqHistoryIntervalTimeframeAsync request using beginFilterTime and endFilterTime. Note I did successfully use the filter function filtering between 930a and 10a.

`lookupClient.Historical.ReqHistoryIntervalTimeframeAsync(
				                                            symbol: dto.Symbol.Symbol,
				                                            interval: ONE_MINUTE_IN_SECONDS,
				                                            beginDate: dto.StartDateTime,
				                                            endDate: endDateTime,
															beginFilterTime: new TimeSpan(9, 30, 0),
															endFilterTime: new TimeSpan(16, 0, 0));`

**Comment by jphiggs** [comment] 2019-03-18 18:39
Not sure if this is related to @hunterfries' issue but over the weekend I was getting an IQFeed exception when using the BasicHistorical Example for Historical.ReqHistoryIntervalDaysAsync. The inner exception was "Invalid number of parameters'. That didn't occur with the other 2 historical requests in step 5 for that example. The exception also does not occur if I hard code the IQFeed request to
var request = $"HID,AAPL,300,5,100,,,,,,{IQFeedDefault.ProtocolTerminatingCharacters}"; in the historical request formatter. Bottom line is that the formatter will include 7 commas for the optional parameters in the request and that is correct according to the IQFeed documenation, but the exception occurs with seven commas and works with 6. There are also several of the ApiClient tests that are failing for historical requests.

**Comment by mathpaquette** [comment] 2019-03-18 23:40
@jphiggs @hunterfries just ran all the tests and now everything seems to be fine. Can we suppose there was some instability during the weekend not related to the ApiClient?

**Comment by jphiggs** [comment] 2019-03-19 00:10
I still get the 'Invalid number of parameters' exception in the BasicHistoricalExample for the lookupClient.Historical.ReqHistoryIntervalDaysAsync("AAPL", 300, 5, 100); request:

![image](https://user-images.githubusercontent.com/6563358/54571362-fc228e80-49a7-11e9-977d-846dc34228eb.png)

It works if I eliminate one of the optional parameters in the  HistoricalRequestFormatter for an IntervalDays request
 
And still have failing tests for historical requests.  
![image](https://user-images.githubusercontent.com/.6563358/54571246-71da2a80-49a7-11e9-8f50-36cabac6d53c.png)

**Comment by jphiggs** [comment] 2019-03-19 00:12
![image](https://user-images.githubusercontent.com/6563358/54571641-596b0f80-49a9-11e9-83c6-efc45129bdff.png)

**Comment by mathpaquette** [comment] 2019-03-19 00:17
@jphiggs just ran all the tests with IQFeed version 6.0.0.5 without any issue. What version you got?

**Comment by mathpaquette** [comment] 2019-03-19 00:18
looks like a regression from IQFeed

**Comment by jphiggs** [comment] 2019-03-19 00:26
Yep, still on 5.2.5.0 and I'll change that but thought the default ProtocolVersion = "5.2"; definition would have prevented a conflict.  I'll get back with the result after I upgrade.

**Comment by mathpaquette** [comment] 2019-03-19 00:33
Oh... of course you need to be in sync with the latest version of the Client...
Just tested with the 6.0.1.1 and everything is green on my side.

![image](https://user-images.githubusercontent.com/4358455/54572286-174bc900-49bd-11e9-8c95-90c4028f0250.png)

**Comment by mathpaquette** [comment] 2019-03-19 00:36
@jphiggs just tested your query and also works fine. Ill close the issue, reopen is you fine something new. Thanks guys.

**Closed by mathpaquette** 2019-03-19 00:36 UTC
Labels: question

**Comment by jphiggs** [comment] 2019-03-19 00:47
Ok, that was it, thanks.
